SASL/SSL examples
runabove/queue-examples pull request #15
Opened 2016-12-06 15:39 UTC by thbkrkr

2016-12-06 17:22 UTC, yadutaf commented
Hmm ? I'd place the examples in a dedicated repo rather than the documentation. What do you think ?

2016-12-07 14:24 UTC, yadutaf commented
My bad. Repository confusion. Please ignore the last comment.

2016-12-08 12:52 UTC, sebgl requested changes
A few general comments on top of the ones below:
* it would make sense to tag docker images as "ovhqueue/py-client-example" instead of "qaas/py-client-example"
* one Makefile per language instead of a big global Makefile would be cleaner

2016-12-08 12:52 UTC, sebgl commented on README.md
> +Here is Kafka client examples using SASL/SSL in several languages and tested on [OVH Queue](https://www.ovh.com/fr/order/express/#/new/express/resume?productId=paasqueue&products=~(~(planCode~'qaas_b
"Here is" -> "Here are"

2016-12-08 12:52 UTC, sebgl commented on README.md
> +and require four flags:
require -> requires

2016-12-08 12:52 UTC, sebgl commented on README.md
> +Here is Kafka client examples using SASL/SSL in several languages and tested on [OVH Queue](https://www.ovh.com/fr/order/express/#/new/express/resume?productId=paasqueue&products=~(~(planCode~'qaas_b
I would set the OVH Queue link to https://www.runabove.com/dbaas-queue.xml instead of the order page.

2016-12-08 12:52 UTC, sebgl commented on README.md
> +    --broker    the Kafka broker adress
adress -> address

2016-12-08 12:52 UTC, sebgl commented on Makefile
>  ## Build Docker images
Should we also add a build-docker-java target?

2016-12-08 12:52 UTC, sebgl commented on kafkacat/kcat
> +  docker run --rm -i krkr/kafkacat \
krkr/kafkacat does not exist. Maybe create a Makefile here to build the image locally with a predefined name ("kafkacat") instead.

2016-12-08 12:52 UTC, sebgl commented on Makefile
>  		make build-go-in-docker && \
does not work since there is no Makefile in the go directory

2016-12-08 12:52 UTC, sebgl commented on kafkacat/kcat
> +    -X sasl.username=$SASL_USER \
Use $SASL_USERNAME as other examples

2016-12-08 12:52 UTC, sebgl commented on README.md
> +Install dependencies:
I would prefer setting kafka-python version 1.3.1 as an explicit dependency in the documentation, and put the pip command in the README instead of the "make python-install-deps" that forces me to go through the Makefile to check what it's actually doing on my system.

2016-12-08 12:52 UTC, sebgl commented on kafkacat/kcat
> +    _kafkacat -C -G $SASL_USER.group-kafkacat
Does not seem to work for me; but does work by inverting the two flags:
_kafkacat -G $SASL_USER.group-kafkacat -C

2016-12-08 12:52 UTC, sebgl commented on nodejs/client.js
> +);
My linter complains about missing semi-columns at the end of several statements. Nothing important but let's be consistent and put them everywhere.

2016-12-08 16:57 UTC, merged